{{- if (eq .Values.ingress.kind "istio") }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}-app
spec:
  hosts:
    - "*"
  gateways:
    - aistudio-gateway
  http:
    - match:
        - uri:
            prefix: /{{ .Chart.Name }}/
      rewrite:
        uri: "/"
      headers:
        request:
          set:
            From: "fronted"
            X-Internal-Req: "false"
      route:
        - destination:
            host: {{ .Chart.Name }}
            port:
              number: {{ .Values.service.port }}
  {{- end}}
